// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly [
            'light',
            'dark',
            'amethyst-dark',
            'obsidian-dark',
            'rose-gold-dark',
            'emerald-dark',
            'champagne-dark',
            'sapphire-dark',
            'slate-dark',
            'coral-dark',
            'amethyst-light',
            'obsidian-light',
            'rose-gold-light',
            'emerald-light',
            'champagne-light',
            'sapphire-light',
            'slate-light',
            'coral-light',
        ]
    }
}

export {}
